# Delete these routes and define your own shop routes here

hehepay_sylius_example_static_welcome:
  path: /static-welcome/{name}
  defaults:
    _controller: HeHePay\SyliusPaymentPlugin\Controller\GreetingController::staticallyGreetAction
    name: ~

hehepay_sylius_example_dynamic_welcome:
  path: /dynamic-welcome/{name}
  defaults:
    _controller: HeHePay\SyliusPaymentPlugin\Controller\GreetingController::dynamicallyGreetAction
    name: ~
